code_categoria:
    resource: "@CodeCategoriaBundle/Controller/"
    type:     annotation
    prefix:   /

code_car:
    resource: "@CodeCarBundle/Controller/"
    type:     annotation
    prefix:   /cars/

code_produto:
    resource: "@CodeProdutoBundle/Controller/"
    type:     annotation
    prefix:   /produtos/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
